// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckResumeFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDownloadPath():Promise<string>;

export function GetLogs():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportTableFromExcel(arg1:string):Promise<Array<any>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function PackResumes(arg1:{[key: string]: {[key: string]: Array<string>}}):Promise<string>;

export function RunRPA(arg1:Array<string>):Promise<void>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SayHi():Promise<string>;

export function UpdateOmo(arg1:Array<{[key: string]: any}>):Promise<Array<{[key: string]: any}>>;
