// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckResumeFile(arg1, arg2) {
  return window['go']['main']['App']['CheckResumeFile'](arg1, arg2);
}

export function GetDownloadPath() {
  return window['go']['main']['App']['GetDownloadPath']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportTableFromExcel(arg1) {
  return window['go']['main']['App']['ImportTableFromExcel'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RunRPA(arg1) {
  return window['go']['main']['App']['RunRPA'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function UpdateOmo(arg1) {
  return window['go']['main']['App']['UpdateOmo'](arg1);
}
